version: '3.8'
services:
  cs:
    build: .
    container_name: csgo
    environment:
      - STEAM_API_KEY=value
      - STEAM_GAMESERVER_TOKEN=value
      - RCON_PASSWORD=
    ports:
      - "27015:27015"
      - "27015:27015/udp"