version: '3.8'

services:
  skyrim:
    image: tiltedphoques/st-reborn-server:latest
    container_name: skyrim
    volumes:
      - ./config:/home/server/config
      - ./logs:/home/server/logs
    ports:
      - 10578:10578/udp
    restart: unless-stopped
