version: '3.8'

services:
  skyrim:
    image: tiltedphoques/st-reborn-server:latest
    container_name: skyrim
    volumes:
      - ./config:/opt/docker/skyrimserver/config
      - ./data:/opt/docker/skyrimserver/Data
      - ./logs:/opt/docker/skyrimserver/logs
    ports:
      - 10578:10578/udp
    restart: unless-stopped
