version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: mc.web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/minecraft.conf
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - mc

  router:
    image: itzg/mc-router
    container_name: mc.router
    ports:
      - 25565:25565
    links:
      - mc
    command: --mapping=mc.ak.gg=mc:25565

  mc:
    image: itzg/minecraft-server:java17
    container_name: mc
    environment:
      EULA: "true"
      TYPE: "PAPER"
      VERSION: "1.19.1"
      MOTD: ""
      RCON_PASSWORD: ""
      SLACK_BOT_TOKEN: ""
      SLACK_SIGNING_SECRET: ""
      UID: 1000
      GID: 1000
    ports:
      - 25565
    volumes:
      - ./data:/data
