version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/cryptic.conf
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - crypticmc

  mc-router:
    image: itzg/mc-router
    ports:
      - 25565:25565
    links:
      - crypticmc
    command: --mapping=mc.ak.gg=crypticmc:25565,mc.cryptic.house=crypticmc:25565

  crypticmc:
    image: itzg/minecraft-server:java17
    container_name: mc.cryptic
    environment:
      EULA: "true"
      TYPE: "PAPER"
      VERSION: "1.19.1"
      MOTD: ""
      RCON_PASSWORD: ""
      SLACK_BOT_TOKEN: ""
      SLACK_SIGNING_SECRET: ""
      UID: 1000
      GID: 1000
    ports:
      - 25565
    volumes:
      - ./data:/data
